language: python
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - pip install -r requirements.txt
  - pip install pytest-mock

script:
  - pytest

  env:
  - CODECOV_TOKEN=f2cc82e4-132c-454e-a01c-5fdf8853078d

  after_success:
  - codecov
